// <auto-generated />
using System;
using Library_ManagementAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library_ManagementAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230222022658_ILibrary")]
    partial class ILibrary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Library_ManagementAPI.Models.BooksModels", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("bookAutor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("bookCopies")
                        .HasColumnType("int");

                    b.Property<string>("bookEdition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bookGenres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("bookPgNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("bookPublication")
                        .HasColumnType("datetime2");

                    b.Property<string>("bookPublisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bookResume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bookSubTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bookTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("BooksPropety");
                });
#pragma warning restore 612, 618
        }
    }
}
